Repository FredHutch/wdl-unit-tests, pull requests merged in 2025-02, with the labels that each got.

#80 Adding Docker image check to HelloDockerHostname
  helloDockerHostname/README.md
  helloDockerHostname/helloDockerHostname.wdl
  helloDockerHostname/inputs.json
Labels: unit test

#29 Adding initial version of conditional unit test WDL
  conditionalTest/README.md
  conditionalTest/conditionalTest.wdl
  conditionalTest/inputs.json
  conditionalTest/options.json
Labels: unit test

#60 Adding initial version of nonstandard outputs WDL unit test
  nonstandardOutputs/README.md
  nonstandardOutputs/nonstandardOutputs.wdl
  nonstandardOutputs/options.json
Labels: unit test

#96 11 glob subdir
  globSubdir/README.md
  globSubdir/globSubdir.wdl
  globSubdir/options.json
Labels: unit test

#97 11 glob unmatched
  globNonmatching/README.md
  globNonmatching/globNonmatching.wdl
  globNonmatching/options.json
Labels: unit test

#108 rewrite cassettes: change workflow name and run on workflow dispatch too
  .github/workflows/api-rewrite-cassettes.yml
Labels: infrastructure

#101 43 nested json handling
  testNestedJsonArray/README.md
  testNestedJsonArray/inputs.json
  testNestedJsonArray/options.json
  testNestedJsonArray/testNestedJsonArray.wdl
Labels: unit test

#99 44 same json use by multiple tasks
  jsonTaskOrderTest/README.md
  jsonTaskOrderTest/inputs.json
  jsonTaskOrderTest/jsonTaskOrderTest.wdl
  jsonTaskOrderTest/options.json
Labels: unit test

#27 Adding unit test WDL for struct and map datatype inputs
  .gitignore
  mapTypeTest/README.md
  mapTypeTest/inputs.json
  mapTypeTest/mapTypeTest.wdl
  mapTypeTest/options.json
  structTypeTest/README.md
  structTypeTest/inputs.json
  structTypeTest/options.json
  structTypeTest/structTypeTest.wdl
Labels: unit test

#93 update api-tests workflows with 1password secrets usage
  .github/workflows/api-rewrite-cassettes.yml
  .github/workflows/api-tests.yml
Labels: infrastructure

#122 Adding missing options json's to existing WDL unit tests
  WildcardsandConditions/options.json
  badRunParseBatchFile/options.json
  badValMissingValue/options.json
  basicTaskExecution/options.json
  testFileoperations/options.json
Labels: unit test

#131 added notes about cassettes in contrib and readme
  .github/CONTRIBUTING.md
  README.md
Labels: documentation
