Repository FredHutch/wdl-unit-tests, pull requests merged in 2025-01, with the labels that each got.

#23 Unit test: Basic task execution
  basicTaskExecution/README.md
  basicTaskExecution/basicTaskExecution.wdl
Labels: unit test

#55 Update README.md
  README.md
Labels: documentation

#56 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#51 some new tests, and reconfiguring
  .github/CONTRIBUTING.md
  .github/workflows/api-tests.yml
  badRunParseBatchFile/README.md
  badRunParseBatchFile/badRunParseBatchFile.wdl
  badValMissingValue/README.md
  badValMissingValue/badValMissingValue.wdl
  tests/cromwell-api/cromwell.py
  tests/cromwell-api/test-metadata.py
  tests/cromwell-api/test-submit.py
  tests/cromwell-api/utils.py
  tests/cromwellapi/conftest.py
  tests/cromwellapi/cromwell.py
  tests/cromwellapi/labels1.json
  tests/cromwellapi/proof.py
  tests/cromwellapi/test-abort.py
  tests/cromwellapi/test-call.py
  tests/cromwellapi/test-failures.py
  tests/cromwellapi/test-labels.py
  tests/cromwellapi/test-metadata.py
  tests/cromwellapi/test-outputs.py
  tests/cromwellapi/test-search.py
  tests/cromwellapi/test-submit.py
  tests/cromwellapi/test-validate.py
  tests/cromwellapi/test-version.py
  tests/cromwellapi/utils.py
  tests/cromwelljava/conftest.py
  tests/cromwelljava/test-run.py
  tests/cromwelljava/test-validate.py
  tests/cromwelljava/utils.py
Labels: infrastructure

#64 Update helloDockerHostname.wdl
  helloDockerHostname/helloDockerHostname.wdl
Labels: unit test

#34 added cromwell tests docs in readme
  README.md
Labels: documentation

#84 Proof hardening
  tests/cromwellapi/cromwell.py
  tests/cromwellapi/proof.py
  tests/cromwellapi/utils.py
Labels: infrastructure

#82 Incorporated vcr to speed up tests and make final state tests more feasible
  .github/workflows/api-rewrite-cassettes.yml
  .github/workflows/api-tests.yml
  pyproject.toml
  tests/cromwellapi/cassettes/test-abort/test_abort[helloDockerHostname].yaml
  tests/cromwellapi/cassettes/test-abort/test_abort[helloHostname].yaml
  tests/cromwellapi/cassettes/test-abort/test_abort[helloModuleHostname].yaml
  tests/cromwellapi/cassettes/test-call/test_call_final.yaml
  tests/cromwellapi/cassettes/test-call/test_call_initial.yaml
  tests/cromwellapi/cassettes/test-failures/test_failures_final.yaml
  tests/cromwellapi/cassettes/test-failures/test_failures_initial.yaml
  tests/cromwellapi/cassettes/test-labels/test_labels.yaml
  tests/cromwellapi/cassettes/test-metadata/test_metadata_final.yaml
  tests/cromwellapi/cassettes/test-metadata/test_metadata_initial.yaml
  tests/cromwellapi/cassettes/test-outputs/test_outputs.yaml
  tests/cromwellapi/cassettes/test-search/test_search_no_results.yaml
  tests/cromwellapi/cassettes/test-search/test_search_results.yaml
  tests/cromwellapi/cassettes/test-submit/test_submit_works.yaml
  tests/cromwellapi/cassettes/test-validate/test_validate_bad_wdl.yaml
  tests/cromwellapi/cassettes/test-validate/test_validate_good_wdl.yaml
  tests/cromwellapi/cassettes/test-version/test_version.yaml
  tests/cromwellapi/conftest.py
  tests/cromwellapi/constants.py
  tests/cromwellapi/cromwell.py
  tests/cromwellapi/cromwell_final.py
  tests/cromwellapi/mocked_submissions.json
  tests/cromwellapi/mocks.py
  tests/cromwellapi/proof.py
  tests/cromwellapi/test-abort.py
  tests/cromwellapi/test-call.py
  tests/cromwellapi/test-failures.py
  tests/cromwellapi/test-labels.py
  tests/cromwellapi/test-metadata.py
  tests/cromwellapi/test-outputs.py
  tests/cromwellapi/test-search.py
  tests/cromwellapi/test-submit.py
  tests/cromwellapi/test-validate.py
  tests/cromwellapi/test-version.py
  tests/cromwellapi/utils.py
  tests/cromwellapi/utils_cassettes.py
Labels: infrastructure
